### ISSUE TITLE
Wont install

### ISSUE THREAD

**Issue by corped12** [daniel5151/clicky#15]
i tried to install clicky desktop and trying to install it gave me this error "error: failed to parse manifest at `/home/corped/Cargo.toml`

Caused by:
  no targets specified in the manifest
  either src/lib.rs, src/main.rs, a [lib] section, or [[bin]] section must be present"

**Comment by jeanthom** [comment]
Hi,

Could you be more specific about the command you were trying to run, and from which directory you were trying to run it?

**Comment by corped12** [comment]
I was trying to run it from my home directory

**Comment by jeanthom** [comment]
You need to run the cargo commands from the clicky-desktop directory.
