### ISSUE TITLE
Move minifb to main thread

### ISSUE THREAD

**Issue by Ruben2003-source** [daniel5151/clicky#4]
A call to move the minifb code to main thread for macos and other distros that require minifb to be on the main thread. More info in discord #general and #dev

clicky-desktop/src/main.rs
clicky-desktop/src/backends/minifb.rs

**Comment by daniel5151** [comment]
Closed via [0cfcd94](https://github.com/daniel5151/clicky/commit/0cfcd944909d52427e53ebf1c3fcf1f2b50203d4)
