### ISSUE TITLE
[Close Me] fun fact

### ISSUE THREAD

**Issue by upintheairsheep** [daniel5151/clicky#6]
i found more dumps of unusual devices
https://www.vtolabs.com/iot-forensics
https://realitynet-my.sharepoint.com/personal/mattia_epifani_realitynet_eu/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fmattia_epifani_realitynet_eu%2FDocuments%2FAPPLE_DATASET

**Comment by daniel5151** [comment]
to reiterate: opening Github issues on unrelated projects really isn't the appropriate avenue for sharing these links and ideas.
